aws_region            = "us-east-2"
state_file            = "kreverson-us-east-2-terraform-statefile"
environment           = "dev"
db_name               = "techfood_prd"
db_username           = ""
db_password           = ""