name: Terraform Deploy (PRD only)

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Plan for Production
        run: terraform -chdir=infra plan -var-file="prd/terraform.prd.tfvars"

      - name: Terraform Apply
        run: terraform -chdir=infra apply -auto-approve -var-file="prd/terraform.prd.tfvars"
