name: Terraform Destroy PRD

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type YES to confirm destruction"
        required: true

jobs:
  destroy:
    name: Destroy Resources in PRD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Confirm destruction
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "YES" ]; then
            echo "Destruction not confirmed. Exiting..."
            exit 1
          fi

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -var-file="prd/terraform.prd.tfvars"

      - name: Terraform Destroy (PRD)
        run: terraform destroy -auto-approve -var-file="prd/terraform.prd.tfvars"
